{
  "checkpoints": [
    "{\n  \"stub\": false,\n  \"trainable_name\": \"wrapper\",\n  \"trial_id\": \"be25c_00003\",\n  \"config\": {\n    \"datafile\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005958e000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c0464617461948c0970726f636573736564948c08646174612e6e707994749452942e\"\n    },\n    \"units\": 104,\n    \"dense_layers\": 4,\n    \"activation\": \"relu\",\n    \"optimizer\": \"Adam\",\n    \"epochs\": 30,\n    \"local_dir\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005957f000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c066d6f64656c73948c0372617994749452942e\"\n    },\n    \"log_dir\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"80059584000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c046c6f6773948c0a687970657274756e656494749452942e\"\n    },\n    \"samples\": 10,\n    \"grace_period\": 3,\n    \"modulepath\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005952a000000000000008c07706174686c6962948c0b57696e646f7773506174689493948c022e2e948c0373726394869452942e\"\n    }\n  },\n  \"local_dir\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\",\n  \"evaluated_params\": {\n    \"units\": 104,\n    \"dense_layers\": 4\n  },\n  \"experiment_tag\": \"3_dense_layers=4,units=104\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"placement_group_factory\": \"800595a6000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c155f686561645f62756e646c655f69735f656d70747994898c085f62756e646c6573945d947d948c034350559447401000000000000073618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\",\n  \"stopping_criterion\": {\n    \"training_iteration\": 1\n  },\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"_last_result\": {\n    \"trial_id\": \"be25c_00003\"\n  },\n  \"_default_result_or_future\": null,\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1643633594.3491824,\n  \"logdir\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\\\\wrapper_be25c_00003_3_dense_layers=4,units=104_2022-01-31_13-53-12\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\\\\wrapper_be25c_00003_3_dense_layers=4,units=104_2022-01-31_13-53-12\\\\error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trial_runner.py\\\", line 924, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\ray_trial_executor.py\\\", line 787, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\client_mode_hook.py\\\", line 105, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\worker.py\\\", line 1713, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=19888, ip=127.0.0.1, repr=<types.ImplicitFunc object at 0x000001942D0B10D0>)\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 625, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 629, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 578, in ray._raylet.execute_task.function_executor\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\function_manager.py\\\", line 609, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 255, in train_buffered\\n    result = self.train()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 314, in train\\n    result = self.step()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 381, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 531, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=19888, ip=127.0.0.1, repr=<types.ImplicitFunc object at 0x000001942D0B10D0>)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 262, in run\\n    self._entrypoint()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 330, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 597, in _trainable_func\\n    output = fn()\\n  File \\\"..\\\\src\\\\models\\\\train_model.py\\\", line 112, in tune_wrapper\\n    from src.models import train_model\\nModuleNotFoundError: No module named 'src'\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"sync_function_tpl\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"has_new_resources\": false,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"stub\": false,\n  \"trainable_name\": \"wrapper\",\n  \"trial_id\": \"be25c_00002\",\n  \"config\": {\n    \"datafile\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005958e000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c0464617461948c0970726f636573736564948c08646174612e6e707994749452942e\"\n    },\n    \"units\": 40,\n    \"dense_layers\": 4,\n    \"activation\": \"relu\",\n    \"optimizer\": \"Adam\",\n    \"epochs\": 30,\n    \"local_dir\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005957f000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c066d6f64656c73948c0372617994749452942e\"\n    },\n    \"log_dir\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"80059584000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c046c6f6773948c0a687970657274756e656494749452942e\"\n    },\n    \"samples\": 10,\n    \"grace_period\": 3,\n    \"modulepath\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005952a000000000000008c07706174686c6962948c0b57696e646f7773506174689493948c022e2e948c0373726394869452942e\"\n    }\n  },\n  \"local_dir\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\",\n  \"evaluated_params\": {\n    \"units\": 40,\n    \"dense_layers\": 4\n  },\n  \"experiment_tag\": \"2_dense_layers=4,units=40\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"placement_group_factory\": \"800595a6000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c155f686561645f62756e646c655f69735f656d70747994898c085f62756e646c6573945d947d948c034350559447401000000000000073618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\",\n  \"stopping_criterion\": {\n    \"training_iteration\": 1\n  },\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"_last_result\": {\n    \"trial_id\": \"be25c_00002\"\n  },\n  \"_default_result_or_future\": null,\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1643633592.271738,\n  \"logdir\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\\\\wrapper_be25c_00002_2_dense_layers=4,units=40_2022-01-31_13-53-12\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\\\\wrapper_be25c_00002_2_dense_layers=4,units=40_2022-01-31_13-53-12\\\\error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trial_runner.py\\\", line 924, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\ray_trial_executor.py\\\", line 787, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\client_mode_hook.py\\\", line 105, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\worker.py\\\", line 1713, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=10700, ip=127.0.0.1, repr=<types.ImplicitFunc object at 0x0000015DD06910D0>)\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 625, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 629, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 578, in ray._raylet.execute_task.function_executor\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\function_manager.py\\\", line 609, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 255, in train_buffered\\n    result = self.train()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 314, in train\\n    result = self.step()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 381, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 531, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=10700, ip=127.0.0.1, repr=<types.ImplicitFunc object at 0x0000015DD06910D0>)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 262, in run\\n    self._entrypoint()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 330, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 597, in _trainable_func\\n    output = fn()\\n  File \\\"..\\\\src\\\\models\\\\train_model.py\\\", line 112, in tune_wrapper\\n    from src.models import train_model\\nModuleNotFoundError: No module named 'src'\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"sync_function_tpl\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"has_new_resources\": false,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"stub\": false,\n  \"trainable_name\": \"wrapper\",\n  \"trial_id\": \"be25c_00005\",\n  \"config\": {\n    \"datafile\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005958e000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c0464617461948c0970726f636573736564948c08646174612e6e707994749452942e\"\n    },\n    \"units\": 32,\n    \"dense_layers\": 2,\n    \"activation\": \"relu\",\n    \"optimizer\": \"Adam\",\n    \"epochs\": 30,\n    \"local_dir\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005957f000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c066d6f64656c73948c0372617994749452942e\"\n    },\n    \"log_dir\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"80059584000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c046c6f6773948c0a687970657274756e656494749452942e\"\n    },\n    \"samples\": 10,\n    \"grace_period\": 3,\n    \"modulepath\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005952a000000000000008c07706174686c6962948c0b57696e646f7773506174689493948c022e2e948c0373726394869452942e\"\n    }\n  },\n  \"local_dir\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\",\n  \"evaluated_params\": {\n    \"units\": 32,\n    \"dense_layers\": 2\n  },\n  \"experiment_tag\": \"5_dense_layers=2,units=32\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"placement_group_factory\": \"800595a6000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c155f686561645f62756e646c655f69735f656d70747994898c085f62756e646c6573945d947d948c034350559447401000000000000073618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\",\n  \"stopping_criterion\": {\n    \"training_iteration\": 1\n  },\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"_last_result\": {\n    \"trial_id\": \"be25c_00005\"\n  },\n  \"_default_result_or_future\": null,\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1643633596.349723,\n  \"logdir\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\\\\wrapper_be25c_00005_5_dense_layers=2,units=32_2022-01-31_13-53-14\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\\\\wrapper_be25c_00005_5_dense_layers=2,units=32_2022-01-31_13-53-14\\\\error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trial_runner.py\\\", line 924, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\ray_trial_executor.py\\\", line 787, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\client_mode_hook.py\\\", line 105, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\worker.py\\\", line 1713, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=480, ip=127.0.0.1, repr=<types.ImplicitFunc object at 0x0000020E78AD10D0>)\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 625, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 629, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 578, in ray._raylet.execute_task.function_executor\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\function_manager.py\\\", line 609, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 255, in train_buffered\\n    result = self.train()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 314, in train\\n    result = self.step()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 381, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 531, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=480, ip=127.0.0.1, repr=<types.ImplicitFunc object at 0x0000020E78AD10D0>)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 262, in run\\n    self._entrypoint()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 330, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 597, in _trainable_func\\n    output = fn()\\n  File \\\"..\\\\src\\\\models\\\\train_model.py\\\", line 112, in tune_wrapper\\n    from src.models import train_model\\nModuleNotFoundError: No module named 'src'\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"sync_function_tpl\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"has_new_resources\": false,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"stub\": false,\n  \"trainable_name\": \"wrapper\",\n  \"trial_id\": \"be25c_00009\",\n  \"config\": {\n    \"datafile\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005958e000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c0464617461948c0970726f636573736564948c08646174612e6e707994749452942e\"\n    },\n    \"units\": 48,\n    \"dense_layers\": 4,\n    \"activation\": \"relu\",\n    \"optimizer\": \"Adam\",\n    \"epochs\": 30,\n    \"local_dir\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005957f000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c066d6f64656c73948c0372617994749452942e\"\n    },\n    \"log_dir\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"80059584000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c046c6f6773948c0a687970657274756e656494749452942e\"\n    },\n    \"samples\": 10,\n    \"grace_period\": 3,\n    \"modulepath\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005952a000000000000008c07706174686c6962948c0b57696e646f7773506174689493948c022e2e948c0373726394869452942e\"\n    }\n  },\n  \"local_dir\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\",\n  \"evaluated_params\": {\n    \"units\": 48,\n    \"dense_layers\": 4\n  },\n  \"experiment_tag\": \"9_dense_layers=4,units=48\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"placement_group_factory\": \"800595a6000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c155f686561645f62756e646c655f69735f656d70747994898c085f62756e646c6573945d947d948c034350559447401000000000000073618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\",\n  \"stopping_criterion\": {\n    \"training_iteration\": 1\n  },\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"_last_result\": {\n    \"trial_id\": \"be25c_00009\"\n  },\n  \"_default_result_or_future\": null,\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1643633606.585838,\n  \"logdir\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\\\\wrapper_be25c_00009_9_dense_layers=4,units=48_2022-01-31_13-53-18\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\\\\wrapper_be25c_00009_9_dense_layers=4,units=48_2022-01-31_13-53-18\\\\error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trial_runner.py\\\", line 924, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\ray_trial_executor.py\\\", line 787, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\client_mode_hook.py\\\", line 105, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\worker.py\\\", line 1713, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=10668, ip=127.0.0.1, repr=<types.ImplicitFunc object at 0x00000200629B10D0>)\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 625, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 629, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 578, in ray._raylet.execute_task.function_executor\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\function_manager.py\\\", line 609, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 255, in train_buffered\\n    result = self.train()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 314, in train\\n    result = self.step()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 381, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 531, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=10668, ip=127.0.0.1, repr=<types.ImplicitFunc object at 0x00000200629B10D0>)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 262, in run\\n    self._entrypoint()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 330, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 597, in _trainable_func\\n    output = fn()\\n  File \\\"..\\\\src\\\\models\\\\train_model.py\\\", line 112, in tune_wrapper\\n    from src.models import train_model\\nModuleNotFoundError: No module named 'src'\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"sync_function_tpl\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"has_new_resources\": false,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"stub\": false,\n  \"trainable_name\": \"wrapper\",\n  \"trial_id\": \"be25c_00007\",\n  \"config\": {\n    \"datafile\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005958e000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c0464617461948c0970726f636573736564948c08646174612e6e707994749452942e\"\n    },\n    \"units\": 104,\n    \"dense_layers\": 3,\n    \"activation\": \"relu\",\n    \"optimizer\": \"Adam\",\n    \"epochs\": 30,\n    \"local_dir\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005957f000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c066d6f64656c73948c0372617994749452942e\"\n    },\n    \"log_dir\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"80059584000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c046c6f6773948c0a687970657274756e656494749452942e\"\n    },\n    \"samples\": 10,\n    \"grace_period\": 3,\n    \"modulepath\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005952a000000000000008c07706174686c6962948c0b57696e646f7773506174689493948c022e2e948c0373726394869452942e\"\n    }\n  },\n  \"local_dir\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\",\n  \"evaluated_params\": {\n    \"units\": 104,\n    \"dense_layers\": 3\n  },\n  \"experiment_tag\": \"7_dense_layers=3,units=104\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"placement_group_factory\": \"800595a6000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c155f686561645f62756e646c655f69735f656d70747994898c085f62756e646c6573945d947d948c034350559447401000000000000073618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\",\n  \"stopping_criterion\": {\n    \"training_iteration\": 1\n  },\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"_last_result\": {\n    \"trial_id\": \"be25c_00007\"\n  },\n  \"_default_result_or_future\": null,\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1643633598.8077745,\n  \"logdir\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\\\\wrapper_be25c_00007_7_dense_layers=3,units=104_2022-01-31_13-53-16\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\\\\wrapper_be25c_00007_7_dense_layers=3,units=104_2022-01-31_13-53-16\\\\error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trial_runner.py\\\", line 924, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\ray_trial_executor.py\\\", line 787, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\client_mode_hook.py\\\", line 105, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\worker.py\\\", line 1713, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=8492, ip=127.0.0.1, repr=<types.ImplicitFunc object at 0x00000248F3E910D0>)\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 625, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 629, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 578, in ray._raylet.execute_task.function_executor\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\function_manager.py\\\", line 609, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 255, in train_buffered\\n    result = self.train()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 314, in train\\n    result = self.step()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 381, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 531, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=8492, ip=127.0.0.1, repr=<types.ImplicitFunc object at 0x00000248F3E910D0>)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 262, in run\\n    self._entrypoint()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 330, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 597, in _trainable_func\\n    output = fn()\\n  File \\\"..\\\\src\\\\models\\\\train_model.py\\\", line 112, in tune_wrapper\\n    from src.models import train_model\\nModuleNotFoundError: No module named 'src'\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"sync_function_tpl\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"has_new_resources\": false,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"stub\": false,\n  \"trainable_name\": \"wrapper\",\n  \"trial_id\": \"be25c_00000\",\n  \"config\": {\n    \"datafile\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005958e000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c0464617461948c0970726f636573736564948c08646174612e6e707994749452942e\"\n    },\n    \"units\": 64,\n    \"dense_layers\": 2,\n    \"activation\": \"relu\",\n    \"optimizer\": \"Adam\",\n    \"epochs\": 30,\n    \"local_dir\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005957f000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c066d6f64656c73948c0372617994749452942e\"\n    },\n    \"log_dir\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"80059584000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c046c6f6773948c0a687970657274756e656494749452942e\"\n    },\n    \"samples\": 10,\n    \"grace_period\": 3,\n    \"modulepath\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005952a000000000000008c07706174686c6962948c0b57696e646f7773506174689493948c022e2e948c0373726394869452942e\"\n    }\n  },\n  \"local_dir\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\",\n  \"evaluated_params\": {\n    \"units\": 64,\n    \"dense_layers\": 2\n  },\n  \"experiment_tag\": \"0_dense_layers=2,units=64\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"placement_group_factory\": \"800595a6000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c155f686561645f62756e646c655f69735f656d70747994898c085f62756e646c6573945d947d948c034350559447401000000000000073618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\",\n  \"stopping_criterion\": {\n    \"training_iteration\": 1\n  },\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"_last_result\": {},\n  \"_default_result_or_future\": null,\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1643633590.2051032,\n  \"logdir\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\\\\wrapper_be25c_00000_0_dense_layers=2,units=64_2022-01-31_13-53-10\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\\\\wrapper_be25c_00000_0_dense_layers=2,units=64_2022-01-31_13-53-10\\\\error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trial_runner.py\\\", line 924, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\ray_trial_executor.py\\\", line 787, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\client_mode_hook.py\\\", line 105, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\worker.py\\\", line 1713, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=25480, ip=127.0.0.1, repr=<types.ImplicitFunc object at 0x000001E026C87280>)\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 625, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 629, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 578, in ray._raylet.execute_task.function_executor\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\function_manager.py\\\", line 609, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 255, in train_buffered\\n    result = self.train()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 314, in train\\n    result = self.step()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 381, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 531, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=25480, ip=127.0.0.1, repr=<types.ImplicitFunc object at 0x000001E026C87280>)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 262, in run\\n    self._entrypoint()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 330, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 597, in _trainable_func\\n    output = fn()\\n  File \\\"..\\\\src\\\\models\\\\train_model.py\\\", line 112, in tune_wrapper\\n    from src.models import train_model\\nModuleNotFoundError: No module named 'src'\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"sync_function_tpl\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"has_new_resources\": false,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"stub\": false,\n  \"trainable_name\": \"wrapper\",\n  \"trial_id\": \"be25c_00008\",\n  \"config\": {\n    \"datafile\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005958e000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c0464617461948c0970726f636573736564948c08646174612e6e707994749452942e\"\n    },\n    \"units\": 48,\n    \"dense_layers\": 2,\n    \"activation\": \"relu\",\n    \"optimizer\": \"Adam\",\n    \"epochs\": 30,\n    \"local_dir\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005957f000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c066d6f64656c73948c0372617994749452942e\"\n    },\n    \"log_dir\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"80059584000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c046c6f6773948c0a687970657274756e656494749452942e\"\n    },\n    \"samples\": 10,\n    \"grace_period\": 3,\n    \"modulepath\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005952a000000000000008c07706174686c6962948c0b57696e646f7773506174689493948c022e2e948c0373726394869452942e\"\n    }\n  },\n  \"local_dir\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\",\n  \"evaluated_params\": {\n    \"units\": 48,\n    \"dense_layers\": 2\n  },\n  \"experiment_tag\": \"8_dense_layers=2,units=48\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"placement_group_factory\": \"800595a6000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c155f686561645f62756e646c655f69735f656d70747994898c085f62756e646c6573945d947d948c034350559447401000000000000073618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\",\n  \"stopping_criterion\": {\n    \"training_iteration\": 1\n  },\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"_last_result\": {\n    \"trial_id\": \"be25c_00008\"\n  },\n  \"_default_result_or_future\": null,\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1643633598.8714278,\n  \"logdir\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\\\\wrapper_be25c_00008_8_dense_layers=2,units=48_2022-01-31_13-53-18\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\\\\wrapper_be25c_00008_8_dense_layers=2,units=48_2022-01-31_13-53-18\\\\error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trial_runner.py\\\", line 924, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\ray_trial_executor.py\\\", line 787, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\client_mode_hook.py\\\", line 105, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\worker.py\\\", line 1713, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=25148, ip=127.0.0.1, repr=<types.ImplicitFunc object at 0x000001BEF82D10D0>)\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 625, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 629, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 578, in ray._raylet.execute_task.function_executor\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\function_manager.py\\\", line 609, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 255, in train_buffered\\n    result = self.train()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 314, in train\\n    result = self.step()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 381, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 531, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=25148, ip=127.0.0.1, repr=<types.ImplicitFunc object at 0x000001BEF82D10D0>)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 262, in run\\n    self._entrypoint()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 330, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 597, in _trainable_func\\n    output = fn()\\n  File \\\"..\\\\src\\\\models\\\\train_model.py\\\", line 112, in tune_wrapper\\n    from src.models import train_model\\nModuleNotFoundError: No module named 'src'\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"sync_function_tpl\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"has_new_resources\": false,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"stub\": false,\n  \"trainable_name\": \"wrapper\",\n  \"trial_id\": \"be25c_00006\",\n  \"config\": {\n    \"datafile\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005958e000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c0464617461948c0970726f636573736564948c08646174612e6e707994749452942e\"\n    },\n    \"units\": 88,\n    \"dense_layers\": 2,\n    \"activation\": \"relu\",\n    \"optimizer\": \"Adam\",\n    \"epochs\": 30,\n    \"local_dir\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005957f000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c066d6f64656c73948c0372617994749452942e\"\n    },\n    \"log_dir\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"80059584000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c046c6f6773948c0a687970657274756e656494749452942e\"\n    },\n    \"samples\": 10,\n    \"grace_period\": 3,\n    \"modulepath\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005952a000000000000008c07706174686c6962948c0b57696e646f7773506174689493948c022e2e948c0373726394869452942e\"\n    }\n  },\n  \"local_dir\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\",\n  \"evaluated_params\": {\n    \"units\": 88,\n    \"dense_layers\": 2\n  },\n  \"experiment_tag\": \"6_dense_layers=2,units=88\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"placement_group_factory\": \"800595a6000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c155f686561645f62756e646c655f69735f656d70747994898c085f62756e646c6573945d947d948c034350559447401000000000000073618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\",\n  \"stopping_criterion\": {\n    \"training_iteration\": 1\n  },\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"_last_result\": {\n    \"trial_id\": \"be25c_00006\"\n  },\n  \"_default_result_or_future\": null,\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1643633596.388619,\n  \"logdir\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\\\\wrapper_be25c_00006_6_dense_layers=2,units=88_2022-01-31_13-53-16\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\\\\wrapper_be25c_00006_6_dense_layers=2,units=88_2022-01-31_13-53-16\\\\error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trial_runner.py\\\", line 924, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\ray_trial_executor.py\\\", line 787, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\client_mode_hook.py\\\", line 105, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\worker.py\\\", line 1713, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=16568, ip=127.0.0.1, repr=<types.ImplicitFunc object at 0x000001E9FAEE10D0>)\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 625, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 629, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 578, in ray._raylet.execute_task.function_executor\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\function_manager.py\\\", line 609, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 255, in train_buffered\\n    result = self.train()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 314, in train\\n    result = self.step()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 381, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 531, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=16568, ip=127.0.0.1, repr=<types.ImplicitFunc object at 0x000001E9FAEE10D0>)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 262, in run\\n    self._entrypoint()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 330, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 597, in _trainable_func\\n    output = fn()\\n  File \\\"..\\\\src\\\\models\\\\train_model.py\\\", line 112, in tune_wrapper\\n    from src.models import train_model\\nModuleNotFoundError: No module named 'src'\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"sync_function_tpl\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"has_new_resources\": false,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"stub\": false,\n  \"trainable_name\": \"wrapper\",\n  \"trial_id\": \"be25c_00004\",\n  \"config\": {\n    \"datafile\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005958e000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c0464617461948c0970726f636573736564948c08646174612e6e707994749452942e\"\n    },\n    \"units\": 96,\n    \"dense_layers\": 2,\n    \"activation\": \"relu\",\n    \"optimizer\": \"Adam\",\n    \"epochs\": 30,\n    \"local_dir\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005957f000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c066d6f64656c73948c0372617994749452942e\"\n    },\n    \"log_dir\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"80059584000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c046c6f6773948c0a687970657274756e656494749452942e\"\n    },\n    \"samples\": 10,\n    \"grace_period\": 3,\n    \"modulepath\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005952a000000000000008c07706174686c6962948c0b57696e646f7773506174689493948c022e2e948c0373726394869452942e\"\n    }\n  },\n  \"local_dir\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\",\n  \"evaluated_params\": {\n    \"units\": 96,\n    \"dense_layers\": 2\n  },\n  \"experiment_tag\": \"4_dense_layers=2,units=96\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"placement_group_factory\": \"800595a6000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c155f686561645f62756e646c655f69735f656d70747994898c085f62756e646c6573945d947d948c034350559447401000000000000073618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\",\n  \"stopping_criterion\": {\n    \"training_iteration\": 1\n  },\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"_last_result\": {\n    \"trial_id\": \"be25c_00004\"\n  },\n  \"_default_result_or_future\": null,\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1643633594.4176521,\n  \"logdir\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\\\\wrapper_be25c_00004_4_dense_layers=2,units=96_2022-01-31_13-53-14\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\\\\wrapper_be25c_00004_4_dense_layers=2,units=96_2022-01-31_13-53-14\\\\error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trial_runner.py\\\", line 924, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\ray_trial_executor.py\\\", line 787, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\client_mode_hook.py\\\", line 105, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\worker.py\\\", line 1713, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=21432, ip=127.0.0.1, repr=<types.ImplicitFunc object at 0x0000025AFAD51100>)\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 625, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 629, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 578, in ray._raylet.execute_task.function_executor\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\function_manager.py\\\", line 609, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 255, in train_buffered\\n    result = self.train()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 314, in train\\n    result = self.step()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 381, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 531, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=21432, ip=127.0.0.1, repr=<types.ImplicitFunc object at 0x0000025AFAD51100>)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 262, in run\\n    self._entrypoint()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 330, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 597, in _trainable_func\\n    output = fn()\\n  File \\\"..\\\\src\\\\models\\\\train_model.py\\\", line 112, in tune_wrapper\\n    from src.models import train_model\\nModuleNotFoundError: No module named 'src'\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"sync_function_tpl\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"has_new_resources\": false,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}",
    "{\n  \"stub\": false,\n  \"trainable_name\": \"wrapper\",\n  \"trial_id\": \"be25c_00001\",\n  \"config\": {\n    \"datafile\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005958e000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c0464617461948c0970726f636573736564948c08646174612e6e707994749452942e\"\n    },\n    \"units\": 32,\n    \"dense_layers\": 2,\n    \"activation\": \"relu\",\n    \"optimizer\": \"Adam\",\n    \"epochs\": 30,\n    \"local_dir\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005957f000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c066d6f64656c73948c0372617994749452942e\"\n    },\n    \"log_dir\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"80059584000000000000008c07706174686c6962948c0b57696e646f777350617468949394288c03633a5c948c055573657273948c074a616e73656e47948c0c6d6c2d32312d6d6173746572948c1a50726f6a656374204d4c2d32312d4765657274204a616e73656e948c096e6f7465626f6f6b73948c046c6f6773948c0a687970657274756e656494749452942e\"\n    },\n    \"samples\": 10,\n    \"grace_period\": 3,\n    \"modulepath\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"8005952a000000000000008c07706174686c6962948c0b57696e646f7773506174689493948c022e2e948c0373726394869452942e\"\n    }\n  },\n  \"local_dir\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\",\n  \"evaluated_params\": {\n    \"units\": 32,\n    \"dense_layers\": 2\n  },\n  \"experiment_tag\": \"1_dense_layers=2,units=32\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"placement_group_factory\": \"800595a6000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c155f686561645f62756e646c655f69735f656d70747994898c085f62756e646c6573945d947d948c034350559447401000000000000073618c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\",\n  \"stopping_criterion\": {\n    \"training_iteration\": 1\n  },\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"_last_result\": {\n    \"trial_id\": \"be25c_00001\"\n  },\n  \"_default_result_or_future\": null,\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1643633592.039366,\n  \"logdir\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\\\\wrapper_be25c_00001_1_dense_layers=2,units=32_2022-01-31_13-53-12\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"c:\\\\Users\\\\JansenG\\\\ml-21-master\\\\Project ML-21-Geert Jansen\\\\notebooks\\\\models\\\\ray\\\\hypertune\\\\wrapper_be25c_00001_1_dense_layers=2,units=32_2022-01-31_13-53-12\\\\error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trial_runner.py\\\", line 924, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\ray_trial_executor.py\\\", line 787, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\client_mode_hook.py\\\", line 105, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\worker.py\\\", line 1713, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(TuneError): \\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=15968, ip=127.0.0.1, repr=<types.ImplicitFunc object at 0x00000192BE807280>)\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 625, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 629, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 578, in ray._raylet.execute_task.function_executor\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\_private\\\\function_manager.py\\\", line 609, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 255, in train_buffered\\n    result = self.train()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 314, in train\\n    result = self.step()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 381, in step\\n    self._report_thread_runner_error(block=True)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 531, in _report_thread_runner_error\\n    raise TuneError(\\nray.tune.error.TuneError: Trial raised an exception. Traceback:\\n\\u001b[36mray::ImplicitFunc.train_buffered()\\u001b[39m (pid=15968, ip=127.0.0.1, repr=<types.ImplicitFunc object at 0x00000192BE807280>)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 262, in run\\n    self._entrypoint()\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 330, in entrypoint\\n    return self._trainable_func(self.config, self._status_reporter,\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\JansenG\\\\Anaconda3\\\\lib\\\\site-packages\\\\ray\\\\tune\\\\function_runner.py\\\", line 597, in _trainable_func\\n    output = fn()\\n  File \\\"..\\\\src\\\\models\\\\train_model.py\\\", line 112, in tune_wrapper\\n    from src.models import train_model\\nModuleNotFoundError: No module named 'src'\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"sync_function_tpl\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"has_new_resources\": false,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}"
  ],
  "runner_data": {
    "_max_pending_trials": 16,
    "_metric": "val_loss",
    "_total_time": 0,
    "_iteration": 80,
    "_has_errored": true,
    "_fail_fast": false,
    "_server_port": null,
    "_cached_trial_decisions": {},
    "_queued_trial_decisions": {},
    "_updated_queue": true,
    "_result_wait_time": 1,
    "_should_stop_experiment": false,
    "_local_checkpoint_dir": "c:\\Users\\JansenG\\ml-21-master\\Project ML-21-Geert Jansen\\notebooks\\models\\ray\\hypertune",
    "_remote_checkpoint_dir": null,
    "_stopper": {
      "_type": "CLOUDPICKLE_FALLBACK",
      "value": "80059527000000000000008c107261792e74756e652e73746f70706572948c0b4e6f6f7053746f707065729493942981942e"
    },
    "_resumed": false,
    "_start_time": 1643633589.958259,
    "_last_checkpoint_time": -Infinity,
    "_session_str": "2022-01-31_13-53-09",
    "checkpoint_file": "c:\\Users\\JansenG\\ml-21-master\\Project ML-21-Geert Jansen\\notebooks\\models\\ray\\hypertune\\experiment_state-2022-01-31_13-53-09.json",
    "_checkpoint_period": "auto",
    "launch_web_server": false
  },
  "stats": {
    "start_time": 1643633589.958259,
    "timestamp": 1643633613.0736897
  }
}